lidar_costmap_node:
  ros__parameters:
    input_topic: "/scan"
    output_topic: "/costmap"
    frame_id: "map"
    resolution: 0.1
    width: 100
    height: 100
    origin_x: -5.0
    origin_y: -5.0

